# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shapleyImportance <- function(corr_regressors, corr_xy, combinations, repeats_factor) {
    .Call(`_flipRegression_shapleyImportance`, corr_regressors, corr_xy, combinations, repeats_factor)
}

